visualization/board/urls.py
from django.urls import path


from . import views

app_name = 'board'

urlpatterns = [
    # ex: /polls/
    path('', views.home, name='board'),
    #path('explorer', views.explorer, name='base'),
    # ex: /polls/5/
    #path('<int:img_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),

]

visualization/datasets/urls.py
from django.urls import path,re_path
from datasets.views import DatasetsMainView, create_dataset
from django.contrib.auth.decorators import login_required
import datasets.views as dataset_views

urlpatterns = [
    path('', login_required(DatasetsMainView.as_view(),login_url='/login/')),
    path('create_dataset/', create_dataset),
    path('<int:ex_id>/', dataset_views.detail_dataset, name='detail'),
    path('<int:dt_id>/<int:img_id>/', dataset_views.detail_image, name='detail_image'),
]

visualization/visualization/urls.py
from django.contrib import admin
from django.urls import include, path
from uploader.views import MainView, file_upload_view
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('board/', include('board.urls'),name='homepage'),
    path('explorer/', include('explorer.urls')),
    path('uploader/', include('uploader.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),

    path('torch_models/', include('torch_model_module.urls')),
    path('datasets/', include('datasets.urls')),
    path('experiments/', include('experiments.urls')),
    #path('uploader/', MainView.as_view()),
    #path('uploader/upload/', file_upload_view, name= 'upload-view'),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visualization/board/models.py
from django.db import models
from django.utils import timezone

import datetime

# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
#     def __str__(self):
#         return self.question_text
#     def was_published_recently(self):
#         return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
#     def __str__(self):
#         return self.choice_text

class ImageModel(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images')
    image_url = models.CharField(max_length=255)

visualization/board/forms.py
from django import forms

from .models import ImageModel

class ButtonForm(forms.Form):
    XAI = forms.CharField()

visualization/board/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.
from django.http import HttpResponse
from .models import ImageModel
from django.shortcuts import render, redirect,get_object_or_404
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login/')
def home(request):
    context = {'user':request.user,'nbar':'home','logged':True}
    return render(request, 'board/home.html',context)


#not used
def index(request):

    image_list = ImageModel.objects.all()
    len_image_list = len(image_list)

    if request.method == 'POST':
        if 'upload_img' in request.POST:
            if request.FILES and request.FILES['img']:
                myfile = request.FILES['img']
                fs = FileSystemStorage()
                filename = fs.save(myfile.name, myfile)
                uploaded_file_url = fs.url(filename)
                img_object = ImageModel(name = filename,image_url=uploaded_file_url)
                img_object.save()
                return render(request, 'board/child.html', {
                    'uploaded_file_url': uploaded_file_url,
                    'len_image_list':len_image_list,
                    'image_list':image_list
                })

        if 'path' in request.POST:
            return render(request, 'board/child.html',
                {'len_image_list':len_image_list,
                'image_list':image_list
                })


    return render(request, 'board/child.html',
    {'len_image_list':len_image_list,
    'image_list':image_list
    })
    
def explorer(request):
    image_list = ImageModel.objects.all()
    len_image_list = len(image_list)
    return render(request, 'board/child.html',
    {'len_image_list':len_image_list,
    'image_list':image_list
    })

def detail(request, img_id):
    
    img = get_object_or_404(ImageModel, pk=img_id)
    context = {'img': img}

    if request.method == 'POST':
        if 'XAI' in request.POST:
            message = 'XAI should happen'
            context.update({'message':message})
            return render(request, 'board/detail.html', context)
        elif 'refresh' in request.POST:
            context = {'img': img}
            return render(request, 'board/detail.html', context)
        elif 'board' in request.POST:
            return redirect('/board')
        elif 'delete' in request.POST:
            ImageModel.objects.filter(id=img_id).delete()
            return redirect('/board')
    
    return render(request, 'board/detail.html', context)

visualization/board/templates/board/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        
         
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>Image dashboard</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'board/style.css' %}">
        <link rel="stylesheet" href="{% static 'uploader/style.css' %}">
        <link rel="stylesheet" href="{% static 'uploader/main.js' %}">
        <link rel="stylesheet" href="{% static 'torch_model_module/style.css' %}">
        <link rel="stylesheet" href="{% static 'torch_model_module/main.js' %}">

        <link rel="stylesheet" href="{% static 'datasets/style.css' %}">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




        <script src="https://unpkg.com/js-image-zoom@0.4.1/js-image-zoom.js" type="application/javascript"></script>
        <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
        <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
        
    </head>
    <body>

        <!-- <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
        </nav> -->


        <div class="sidebar">
            {% block sidebar %}
            <ul>
                <li><a href="/board/">Home</a></li>
                <li><a href="/explorer/">Explorer</a></li>
                {% comment %}<li><a href="{% url 'board:explorer' %}">Explorer</a></li>{% endcomment %}
                <li><a href="/uploader/">Upload</a></li>
                <li><a href="/torch_models/">Models</a></li>
                <li><a href="/datasets/">Datasets</a></li>
                <li><a href="/experiments/">Experiments</a></li>

                {% if user.is_authenticated %}
                <li><a href="/logout/">Log Out</a></li>
                {% else %}
                <li><a href="/login/">Log In</a></li>
                <li><a href="/register/">Register</a></li>
                {% endif %}
            </ul>

            {% endblock %}
        </div>

        <div id="content">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>

    </body>
</html>

visualization/board/templates/board/child.html
{% extends "board/base.html" %}

{% block content %}

        <p> Number of images: {{len_image_list}}</p>

        <div class="container">
            <div class="row">
                {% for img in image_list %}

                    <div class="col">
                        <a href="/board/{{ img.id }}/">
                            <img src="{{img.image_url}}" alt="{{img.name}}" width="224" height="224">
                        </a>
                    </div>

                    {% if forloop.counter0 == 3 %}
                        <div class="w-100"></div>
                    {% endif %}

                {% endfor %}
            </div>
        </div>

{% endblock %}

visualization/board/templates/board/detail.html
<h1>{{img.name}}</h1>

<!--TODO: Make it a link-->
<img src="{{img.image_url}}" alt="{{img.name}}" width="500" height="600">

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" name="XAI" value="XAI"></input>
    <input type="submit" name="refresh" value="Refresh"></input>
    <input type="submit" name="board" value="Back to board"></input>
    <input type="submit" name="delete" value="Delete"></input>
</form>

<!--a href="{% url 'board:detail' img.id %}">Refresh</a-->

{% if message %}
<p>{{message}}</p>
{% endif %}

visualization/board/templates/board/home.html
{% extends "base.html"%}

{% block content %}

        <p> Hello {{user}}</p>

{% endblock %}

visualization/board/templates/board/index.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
         
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>Image dashboard</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'board/style.css' %}">
        <script rel="stylesheet" src="{% static 'board/functions.js' %}"></script> 
        <script src="https://unpkg.com/js-image-zoom@0.4.1/js-image-zoom.js" type="application/javascript"></script>
        <style>

        </style>
    </head>
    <body>


        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="img">
            <button class= "btn" type="submit" name="upload_img">Upload</button>
        </form>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="path">
            <button type="submit">Directory</button>
        </form>

        <div class="drop-zone">
            <span class="drop-zone__promt">Drop file here or click to download</span>
            <input type="file" name="myFile" class="drop-zone__input">
        </div>


        <!--
        <div id="drop_zone" ondrop="dropHandler(event);" ondragover="dragOverHandler(event);">
            <p>Drag one or more files to this Drop Zone ...</p>
        </div>
        -->


        {% if uploaded_file_url %}
        <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
        {% endif %}

        <p> Number of images: {{len_image_list}}</p>



        <div class="container">
            <div class="row">
                {% for img in image_list %}

                    <div class="col">
                        <a href="/board/{{ img.id }}/">
                            <img src="{{img.image_url}}" alt="{{img.name}}" width="224" height="224">
                        </a>
                    </div>

                    {% if forloop.counter0 == 3 %}
                        <div class="w-100"></div>
                    {% endif %}

                {% endfor %}
            </div>
        </div>

    </body>
</html>